### PR TITLE
Added math plugin and modified lib/cssp.php

### PR DESCRIPTION
**Pull request by raymondgeerts**
# !! Deprecated - see issue 128 !!

Added math plugin (completely working), and modified lib/cssp.php (see comments below)

<pre>@constants
    bar:4px
    tmp:3em

@turbine
    compress: 0
    plugins: math

#foo
    padding: 4px

#bar, #foo
    margin: 2px

#test
    margin: 0 2px + $bar 0 3em + $tmp
    padding: $tmp*2 copy(#foo padding)+2px 40/$bar $bar+$bar
    border: copy(#foo margin) solid #ddd
    width: 100px * $bar + 2px
    height: 2em + $tmp - 1em

#test2
    height: $bar * $tmp
</pre>

This will output:

<pre>#foo {
    padding: 4px;
}
#bar, #foo {
    margin: 2px;
}
#test {
    margin: 0 6px 0 6em; /* math plugin: calcutated value */
    padding: 0 6px 10px 8px; /* math plugin: calcutated value */
    border: 2px solid #ddd;
    width: 402px; /* math plugin: calcutated value */
    height: 4em; /* math plugin: calcutated value */
}
#test2 {
    height: 4px * 3em; /* math plugin: incompatible units px, em */
}
</pre>

---

Modification for lib/cssp.php
This modification will fix copy() value when:

<pre>#bar, #foo
    margin: 2px

#test
    border: copy(#foo margin) solid #ddd
</pre>

it will output:

<pre>#test { 
    border: 2px solid #ddd; 
}
</pre>

before the modification it would output:

<pre>#test { 
    border: 2px; 
}
</pre>

<hr />

This works also in combination with the math plugin.

<pre>@constants
    bar:4px

@turbine
    compress: 0
    plugins: math

#bar, #foo
    margin: 2px

#test
    border: copy(#foo margin)+$bar solid #ddd
</pre>

will output:

<pre>#test { 
    border: 6px solid #ddd; /* math plugin: calcutated value */
}
</pre>

### CODE REVIEW

**Comment by SirPepe** [comment]
Looks fine to me. Let me just get Schepp, my co-author, to take a final look before I pull your changes.

**Comment by raymondgeerts** [comment]
ok great, let me know if there is something like bugs, modifications or feature request.

**Comment by SirPepe** [comment]
The good news: Schepp had nothing to complain about :) But after some testing I found three little issues. First: with error_reporting set to E_ALL the plugin throws some notices. It would be nice if we could get rid of these.

Second: Trying to divide something by zero results in a PHP error. We should catch these case before PHP, attempt no calculation and report the problem via `$cssp->report_error()`. I guess while we're at it we could also report unit mismatches.

Third: What's up here?

```
-- Input:
#foo
    background-positon: 12px * 2 12px / 2

-- Output:
#foo {
    background-positon: 0 6px; /* math plugin: calcutated value */
}
```

**Comment by raymondgeerts** [comment]
I will look in to these bugs/warnings probably this week. The first two should not be a big problem to fix.
The third is unexpected something strange that should not happen.

**Comment by raymondgeerts** [comment]
I dont get any notices with error_reporting E_ALL
Im running Apache 2.2.14 with PHP 5.3.1
Also deviding by zero doesnt give any errors here.

i have set the debug_level to 2 and even added the error_reporting E_ALL to the math.php and css.php files

**Comment by raymondgeerts** [comment]
third problem is fixed, i modified background-positon to background-position and fixed the problem where the first value was output as 0

**Comment by SirPepe** [comment]
Ok, I'm still getting notices but I can fix that myself. Some more bugs:

```
#foo
    font-size:0 + 0 + 12px + 12px

#foo {
    font-size: 24px 12px + 12px; /* math plugin: calcutated value */
}
```

And:

```
#foo
    font-size:12px * -1

#foo {
    font-size: 12px * -1; /* math plugin: calcutated value */
}
```

And:

```
#foo
    font-size:1px + 2px * 2
#foo {
    font-size: 6px; /* math plugin: calcutated value */
}
```

Why not just check the units and use eval? Math ist hard.

**Pull request closed without merging**
